# Generated by Django 4.0 on 2021-12-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(default='Type anythink', max_length=500)),
                ('auther', models.CharField(default='Admin', max_length=50)),
                ('group', models.CharField(default='Public', max_length=50)),
                ('comment', models.IntegerField(default=1)),
                ('content', models.TextField(default='Admin')),
            ],
        ),
    ]
