# Generated by Django 4.0 on 2021-12-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='group',
            field=models.CharField(choices=[('Fasion', 'Fasion'), ('Models', 'Models'), ('Classes', 'Classes')], default='Public', max_length=50),
        ),
    ]
