# Generated by Django 4.0 on 2022-01-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0004_alter_blog_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
    ]
